### ISSUE TITLE
Working with wayland

### ISSUE THREAD

**Issue by KristianKarl** [shenlebantongying/qAngle#1]
When using it on wayland, I get this message:
```bash
❯ ./build/qangle
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""

```

Isa it expected to work on wayland?

Additional info.
* Compiled and run from commit ac6fa59c53f23c7a3a34db4b331d67c7ffa29d7e

```
Operating System: Ubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-20-generic (64-bit)
Graphics Platform: Wayland
```

**Comment by shenlebantongying** [comment]
> Isa it expected to work on wayland?

It works on my machine's kde wayland :)

---

You probably need to install `qt6-wayland`. https://packages.ubuntu.com/jammy/qt6-wayland

Also, try `QT_QPA_PLATFORM=xcb`.

If it is just a warning, then ignore it.

**Comment by KristianKarl** [comment]
I did not have `qt6-wayland`,  so I installed that, and `qt6-wayland-dev` while I was at it.
Now works great! 
Thank you very much :pray: 

Great little tool btw :100:
